### ISSUE TITLE
Cardholder is missing

### ISSUE THREAD

**Issue by stdclass** [wirecard/magento2-wcs#31] opened 2017-10-27 07:31 UTC
After installing the Magento2 version of the plugin and completing the checkout process, I get the error "Cardholder is missing" in the frontend.
The checkout method is **Wirecard Checkout Seamless Credit Card**.
The checkout is currently set to Test and I tested with several testing creditcards (non-3d secure, 3d secure etc..)

Magento ver. 2.1.9
magento2-wcs ver. 1.0.7

In the debug.log I see the following message:
[2017-10-25 11:12:04] main.DEBUG: `Wirecard\CheckoutSeamless\Controller\Checkout\Back::execute:Magento orderCreation is missing {"is_exception":false} []`

**Comment by rinnhofer** [comment] 2017-10-27 07:33
Hello,
thank you for moving the issue. We will look into it as soon as possible.

Cheers

**Comment by tomazpu** [comment] 2017-11-07 07:56
Hello,
we cannot reproduce the error you are getting. Can u give us addition information?

best regards

**Comment by tomazpu** [comment] 2017-11-16 08:45
Hello, 
i will close the issue, please open a new one if you still have the issue.

best regards

**Closed by tomazpu** 2017-11-16 08:45 UTC
