### ISSUE TITLE
Capture without order (billing address)

### ISSUE THREAD

**Issue by marcmayo** [wirecard/magento2-wcs#23] opened 2017-10-02 13:18 UTC
Hi,
a customer got charged even tho he didn't order because there was a problem with the billing address.
Steps to reproduce:
Enter shipping address
on billing page tick "enter another billing address"
enter everything but no zip code
click "place order"
you get an error that the zip code is not correct but the card gets charged

**Comment by jakubpolomsky** [comment] 2017-10-03 06:41
Hi,

thank you for your time writing this. There are some issues though regarding this behavior.

Our plugin is tested against the Luma template (default) and there is no tick "enter another billing address" I can only untick "My billing and shipping address are the same", this disables the button "place order" and creates a new fieldset with all the address related parameters and adds a new button called "Update" without filling the ZIP it's not possible to continue. If you use a non-standard template it is unfortunately up to you or up to the creator of that template to foresee these possible issues.

If I am wrong thinking you are using something non stanrard, please correct me and point me to the right direction with a more comprehensive guide how to reproduce these errors.

Please answer as soon as possible so that we can help you.

BR

**Comment by marcmayo** [comment] 2017-10-03 13:25
Hello @jakubpolomsky 
sorry I used the wrong phrase. It is "My billing and shipping address are the same" in our theme as well. And it works like you described but a user of us still managed to click "place order" for some reason

**Comment by jakubpolomsky** [comment] 2017-10-04 05:50
Hi,

this is unfortunately no error on our side. It doesn't really matter what payment method is chosen, of ours or built in payment methods from Magento, you can still remove the class `disabled` from the button and continue with the process. I will close this issue now. If you find an error in our plugin, please contact us again. Should you have troubles finding the cause of this, I'd suggest removing or disabling extensions which modify the templates of your shop and see if the error can be reproduced. Or setting up a test shop on a subdomain and try to reproduce the behavior there with test credentials.

**Closed by jakubpolomsky** 2017-10-04 05:50 UTC
