### ISSUE TITLE
Unneeded caching of "wirecardcheckoutseamless/checkout/back" url

### ISSUE THREAD

**Issue by archonkulis** [wirecard/magento2-wcs#15] opened 2017-09-01 06:21 UTC
Hi once again.

When customer pays through wirecard with credit card and enters some data, he gets redirected to wirecard site and then back to Magento to this url:

`wirecardcheckoutseamless/checkout/back`

It seems that this url uses some kind of caching based on this -> https://prnt.sc/gfoldm

The problem why caching this url is a bad idea is following:

 - Customer enters incorrect card details -> gets redirected back to Magento with some kind of error message;
 - If customer tries again doing check-out and entering the incorrect card details straight away, he again gets redirected back to Magento, but this time without any error message;

Reason for above seems to be that that url is being cached, but not sure with what kind of mechanism.

At first, I thought it's Varnish cache, but I bypassed the wirecardcheckoutseamless/checkout/back url and still same issue.

Can you please let me know if this is indeed some kind of cache from your extensions side and how to turn it off if it is?

Thanks.

**Comment by jakubpolomsky** [comment] 2017-09-04 14:21
Thank you for the elaboration of the issue. As this is a duplicate of #11 I will close this issue and please follow the development there.

**Closed by jakubpolomsky** 2017-09-04 14:21 UTC

**Comment by archonkulis** [comment] 2017-09-06 08:08
@jakubpolomsky 

Can you please at least say if this indeed could be your extensions caching? I mean, does this extension have any caching implemented at atll? It shouldn't be hard for you to tell also how to turn it off if it is.

Thanks.

**Comment by rinnhofer** [comment] 2017-09-07 05:50
Hello,
sorry for the delayed answer. No there is no extra caching from our plugin, the caching is default behavior from magento2. But we are currently working on a solution for the error messages.

**Comment by archonkulis** [comment] 2017-09-07 06:55
Ok, thanks.

Good luck!
