### ISSUE TITLE
Orders get removed

### ISSUE THREAD

**Issue by marcmayo** [wirecard/magento2-wcs#17] opened 2017-09-07 09:47 UTC
Following case:
A customer tried to checkout using WireCard Credit Card.
The payment fails. He then gets back to the cart and the next time he is choosing normal bank transfer.
The order succeeds and the customer gets a confirmation E-Mail.
But the Order is not created in the backend.

**Comment by rinnhofer** [comment] 2017-09-07 10:37
Hello,
I tried to reproduce your case, but using "Bank Transfer Payment" after failed payment with WirecardCheckoutSeamless CreditCard (with Demodata) did work with normal behavior in my test environment. (order for bank transfer was created) 
Did this happen just once? Maybe you can give me more information to reproduce.

Cheers

**Comment by marcmayo** [comment] 2017-09-07 10:50
Hello @rinnhofer 
we know of 2 times on 2 different days so far but we can't estimate the number of unknown cases.
Our Developer looked into it.
The order got a database entry in "quote" and "quote_payment"

Im checking that failed orders quote in the database and in the payment additional information, there is following:

QPAY-Session timed out after 30 minutes without activity

But the payment method is "bank transfer" which probably got rewritten.

**Comment by archonkulis** [comment] 2017-09-07 11:40
Yep, @marcmayo basically explained the problem in the last comment, but I'll try to comment it from the developers perspective.

So, we have found so far only 2 orders that got deleted and both of them in the `quote_payment.additional_information` have this error in common:

`QPAY-Session timed out after 30 minutes without activity`

But at this point we don't know if it's really because of this error message. We think that it might be, because we tried reproducing the issue by making an unsuccessful order ( and got different error msg, e.g. the one when you just enter incorrect data ), but everything went fine.

At this point, it seems that the flow was following:

Customer created order -> he got redirected back to Magento with error message ( at this point, order got removed ) -> He made an order again with different payment method -> And here at some point, either it didn't even got to the point where it makes an order, or it got removed at some point after making it.

Btw, the settings for order creation must be set to "after". Also, the customer got the order confirmation e-mail.

Could you maybe describe that error more detailed? How could customer get that error? Btw, error code is 99996.

Let me know if you have any questions, not sure if I described everything precisely.

Thanks.

**Comment by rinnhofer** [comment] 2017-09-08 06:35
Thank your @marcmayo and @archonkulis for the detailed description, we will work on a solution as soon as possible and give you feedback when it is done.

Cheers

**Comment by marcmayo** [comment] 2017-09-08 06:52
@rinnhofer after some more investigation it happened to us on 3 orders. For 2 of them we have logs.
I think once the QPay times out it deletes the order.

Order: 29-68179177 successfully placed order at 22:22 (German time) and then the Failure message in the debug log happened at 22:56:00 (German Time) (00 seconds maybe a cron?)
The time in the debug log is 2h behind so please add 2h

2017-08-31 20:56:00 main.DEBUG: Wirecard\CheckoutSeamless\Controller\Checkout\Confirm::execute:Array
(
error_1_errorCode => 99996
error_1_message => QPAY-Session timed out after 30 minutes without activity.
error_1_consumerMessage => Die QPAY-Benutzersitzung wurde nach 30 minütiger Inaktivität beendet.
errors => 1
paymentState => FAILURE
mage_orderId => 29-68179177
mage_quoteId => 435267
mage_orderCreation => after
quoteHash => 8d525beb13a99c0aaec1757e1ee62fe83acce1ed66179418fffd4e49db65d4fcdc64d773b650b6d6c94db6707a96d89e397d565352e050202a74e4c2d330f1e1
)
-----------------------------------------------------
1-48212471 successfully placed order at 22:57 (German time) and the message (FAILURE) from Wirecard happened at 23:30 German time (2h + because of server time)

2017-09-04 21:30:53 main.DEBUG: Wirecard\CheckoutSeamless\Controller\Checkout\Confirm::execute:Array
(
error_1_errorCode => 99996
error_1_message => QPAY-Session timed out after 30 minutes without activity.
error_1_consumerMessage => Die QPAY-Benutzersitzung wurde nach 30 minütiger Inaktivität beendet.
errors => 1
paymentState => FAILURE
mage_orderId => 1-48212471
mage_quoteId => 436436
mage_orderCreation => after
quoteHash => d6cdbbcb908a4d34cf4e5810c1561eb0342e14062b13af4050be42a269028d4de1e975eada5826c996af640c926053a9d6086b27a6694f75f87a1bdc0a781e1c
)

**Comment by rinnhofer** [comment] 2017-09-15 08:17
Hello,
there is a new release of our plugin. Please check if the described problems are solved and let me know so I can close the issue.
Thank you

Cheers

**Comment by rinnhofer** [comment] 2017-09-25 06:35
I suggest your problems got solved by the last release since there was no further feedback. I close this issue now. If there is anything further please feel free to open a new issue or contact our support.

Cheers

**Closed by rinnhofer** 2017-09-25 06:35 UTC
