### ISSUE TITLE
Setup version for module 'Wirecard_CheckoutSeamless' is not specified

### ISSUE THREAD

**Issue by jcserracampos** [wirecard/magento2-wcs#52] opened 2019-05-10 00:48 UTC
### Prerequisites

- [ X ] I have my [server set up correctly](https://guides.wirecard.at/shop_plugins:wcs:magento2:installation).
- [ X ] I am using a [supported version of Magento 2](https://guides.wirecard.at/shop_plugins:wcs:magento2:start).

### Versions

**Magento 2 version:** 2.2.8
**PHP version:** 7.0

### Issue

**Problem description:**

After installing Wirecard WCS with composer, my Magento2 installation crashed with the following error:

`{"0":"Setup version for module 'Wirecard_CheckoutSeamless' is not specified","1":"<pre>#1 Magento\\Framework\\Module\\DbVersionInfo->isSchemaUpToDate('Wirecard_Checkou...') called at [vendor\/magento\/framework\/Module\/DbVersionInfo.php:77]\n#2 Magento\\Framework\\Module\\DbVersionInfo->getDbVersionErrors() called at [vendor\/magento\/framework\/Module\/Plugin\/DbStatusValidator.php:120]\n#3 Magento\\Framework\\Module\\Plugin\\DbStatusValidator->getGroupedDbVersionErrors() called at [vendor\/magento\/framework\/Module\/Plugin\/DbStatusValidator.php:53]\n#4 Magento\\Framework\\Module\\Plugin\\DbStatusValidator->beforeDispatch(&Magento\\Framework\\App\\FrontController\\Interceptor#00000000345f2a03000000003d97a34e#, &Magento\\Framework\\App\\Request\\Http#00000000345f2b4a000000003d97a34e#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:121]\n#5 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Request\\Http#00000000345f2b4a000000003d97a34e#) called at [vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php:69]\n#6 Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(&Magento\\Framework\\App\\FrontController\\Interceptor#00000000345f2a03000000003d97a34e#, &Closure#00000000345f2a05000000003d97a34e#, &Magento\\Framework\\App\\Request\\Http#00000000345f2b4a000000003d97a34e#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#7 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Request\\Http#00000000345f2b4a000000003d97a34e#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#8 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', array(&Magento\\Framework\\App\\Request\\Http#00000000345f2b4a000000003d97a34e#), array(array('storeCookieValid...', 'install', 'configHash'), 'requestPreproces...')) called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#9 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(&Magento\\Framework\\App\\Request\\Http#00000000345f2b4a000000003d97a34e#) called at [vendor\/magento\/framework\/App\/Http.php:136]\n#10 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#11 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:257]\n#12 Magento\\Framework\\App\\Bootstrap->run(&Magento\\Framework\\App\\Http\\Interceptor#00000000345f2b0f000000003d97a34e#) called at [index.php:39]\n<\/pre>","url":"\/nti\/","script_name":"\/nti\/index.php"}`

**Steps to reproduce:**

Install, active, try to access.

**Comment by miha1** [comment] 2019-07-22 14:46
Dear @jcserracampos 
Thank you for your message. We have investigated your issue and could not reproduce that behavior. Consequently we will close it.
Kind regards,
Wirecard Shop Systems Team

**Closed by miha1** 2019-07-22 14:46 UTC
